### ISSUE TITLE
[feature request] avoir une url qui comprenne la requête

### ISSUE THREAD

**Issue by goofy-mdn** [ashgan-dev/ironemes#8]
Hello,

De temps en temps j’aimerais envoyer à des irnonémistes du coin l’adresse d’un résultat de recherche , par exemple 
https://ironemes.eu.org/search&saucisse
ouvrirait direct sur la page des résultats de la recherche d’ironèmes contenant "saucisse".

(un jour où tu ne sais pas quoi faire hein, rien d’important ni d’urgent)

merci, bisous.

**Comment by ashgan-dev** [comment]
la feature est deja la: https://ironemes.eu.org/search/saucisse marche :)
bon, okay, c'est pas dans ma doc inexistante
